#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright 2021 A. Paul Millar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import datetime
import git
import wikidata
import ror
import validation


ror_data = ror.parse_datadump("data/ror-data.json") # FIXME make this configurable.
print("Loaded {} organisations from ROR data dump".format(len(ror_data)))


wikidata_orgs_with_ror = wikidata.query_ror_ids()
print("Wikidata has {} organisations with ROR information".format(len(wikidata_orgs_with_ror)))
print()


count = 0
for qid in wikidata_orgs_with_ror:
    rorId = wikidata_orgs_with_ror[qid]

    if rorId not in ror_data:
        print("{} orphaned link to {}".format(qid, rorId))
        count += 1

print("\nFound {} orphaned links.".format(count))
